// 所有二级导航信息
export default [
    {
        path:'all',
        routeNavName:'全部',
        subType:1
    },
    {
        path:'dianzi',
        routeNavName:'电子信息',
        subType:1
    },
    {
        path:'nengyuan',
        routeNavName:'能源环保',
        subType:1
    },
    {
        path:'zhuangbei',
        routeNavName:'装备制造',
        subType:1
    },
    {
        path:'shengwu',
        routeNavName:'生物制药',
        subType:1
    },
    {
        path:'huagong',
        routeNavName:'化工材料',
        subType:1
    },
    {
        path:'tumu',
        routeNavName:'土木交通',
        subType:1
    },
    {
        path:'other',
        routeNavName:'相关其他',
        subType:1
    },
]