export default [
    {
        routeNavName:'专利申请流程',
        path:'process',
        isArticle:true,
        type:0
    },
    {
        routeNavName:'专利申请指南',
        path:'guidence',
        isArticle:false,
        type:0
    },
    {
        routeNavName:'专利转化',
        path:'transition',
        isArticle:false,
        type:0
    },
    {
        routeNavName:'专利政策法规',
        path:'policy',
        isArticle:false,
        type:0
    },
    {
        routeNavName:'专利表格下载',
        path:'tableDownload',
        isArticle:false,
        type:0
    },
    {
        routeNavName:'专利相关链接',
        path:'links',
        isArticle:true,
        type:0
    },
]